[build]
  command = "npm run build"
  publish = "api"

[context.production.environment]
  SHOW_LOGIN_PAGE = "true"
  MOCKPASS_STATELESS = "true"
  ENCRYPT_MYINFO = "true"

[context.branch-deploy.environment]
  SHOW_LOGIN_PAGE = "true"
  MOCKPASS_STATELESS = "true"
  ENCRYPT_MYINFO = "true"

[template.environment]
  SHOW_LOGIN_PAGE = "Show login page at runtime"
  MOCKPASS_STATELESS = "Set MockPass to run in stateless processes"
  ENCRYPT_MYINFO = "Encrypt MyInfo personas and verify requests"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
